/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlightIdRouteImport } from './routes/flight.$id'
import { Route as ApiPublicHooksDiscoverPricesRouteImport } from './routes/api/public/hooks/discover-prices'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightIdRoute = FlightIdRouteImport.update({
  id: '/flight/$id',
  path: '/flight/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDiscoverPricesRoute =
  ApiPublicHooksDiscoverPricesRouteImport.update({
    id: '/api/public/hooks/discover-prices',
    path: '/api/public/hooks/discover-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/deals': typeof DealsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/search': typeof SearchRoute
  '/flight/$id': typeof FlightIdRoute
  '/api/public/hooks/discover-prices': typeof ApiPublicHooksDiscoverPricesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/deals': typeof DealsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/search': typeof SearchRoute
  '/flight/$id': typeof FlightIdRoute
  '/api/public/hooks/discover-prices': typeof ApiPublicHooksDiscoverPricesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts': typeof AlertsRoute
  '/deals': typeof DealsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/search': typeof SearchRoute
  '/flight/$id': typeof FlightIdRoute
  '/api/public/hooks/discover-prices': typeof ApiPublicHooksDiscoverPricesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/alerts'
    | '/deals'
    | '/opportunities'
    | '/search'
    | '/flight/$id'
    | '/api/public/hooks/discover-prices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/alerts'
    | '/deals'
    | '/opportunities'
    | '/search'
    | '/flight/$id'
    | '/api/public/hooks/discover-prices'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/alerts'
    | '/deals'
    | '/opportunities'
    | '/search'
    | '/flight/$id'
    | '/api/public/hooks/discover-prices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AlertsRoute: typeof AlertsRoute
  DealsRoute: typeof DealsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  SearchRoute: typeof SearchRoute
  FlightIdRoute: typeof FlightIdRoute
  ApiPublicHooksDiscoverPricesRoute: typeof ApiPublicHooksDiscoverPricesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight/$id': {
      id: '/flight/$id'
      path: '/flight/$id'
      fullPath: '/flight/$id'
      preLoaderRoute: typeof FlightIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-prices': {
      id: '/api/public/hooks/discover-prices'
      path: '/api/public/hooks/discover-prices'
      fullPath: '/api/public/hooks/discover-prices'
      preLoaderRoute: typeof ApiPublicHooksDiscoverPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AlertsRoute: AlertsRoute,
  DealsRoute: DealsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  SearchRoute: SearchRoute,
  FlightIdRoute: FlightIdRoute,
  ApiPublicHooksDiscoverPricesRoute: ApiPublicHooksDiscoverPricesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
